# Makefile
#
# Date: March 5, 2016
# Author: Brandon Perez
# Author: Jared Choi
#
# The top-level Makefile for the project, handles compilation for both the
# driver and the example application programs

################################################################################
# Configuration
################################################################################

# Set the shell to BASH
SHELL = /bin/bash

# Allow the user to specify cross-compilation from the command line
CC = $(CROSS_COMPILE)gcc

# Standard gcc flags for compilation
GLOBAL_CFLAGS = -Wall -Wextra -Werror -std=gnu99

# Location of the header files for the AXI DMA library
LIBAXIDMA_INC_DIRS = include
LIBAXIDMA_INC_FILES = libaxidma.h axidma_ioctl.h
LIBAXIDMA_INC = $(addprefix $(LIBAXIDMA_INC_DIRS)/,$(LIBAXIDMA_INC_FILES))
LIBAXIDMA_INC_FLAGS = $(addprefix -I ,$(LIBAXIDMA_INC_DIRS))

# The location where the compiled executables and driver will be stored
OUTPUT_DIR ?= outputs

################################################################################
# Targets
################################################################################

# None of the targets correspond to actual files
.PHONY: all debug clean cross_compiler_check help

# Compile the examples and driver in release mode as the default target
all: driver examples

# Compile the driver and examples in debug mode
debug: driver_debug examples_debug

# Include the specific targets for the examples and driver
include examples/Makefile
include driver/Makefile

# Make the specified output directory, if it doesn't exist
$(OUTPUT_DIR):
	@mkdir -p $(OUTPUT_DIR)

# Clean up all temporary files
clean: driver_clean examples_clean
	rm -rf $(OUTPUT_DIR)

# Check that the specified cross-compiler exists
cross_compiler_check:
ifdef CROSS_COMPILE
ifeq (,$(shell which $(CC)))
	@printf "Error: '$(CROSS_COMPILE)' is not a valid cross-compiler prefix. "
	@printf "'$(CC)' was not found in your path.\n"
	@exit 1
endif
endif

# Display a help message to the user
help:
	@printf "Usage:\n"
	@printf "\tmake [target] [variable] ...\n"
	@printf "\n"
	@printf "Targets:\n"
	@printf "\tall (default)\n"
	@printf "\t    The default target. Compiles both the examples and driver.\n"
	@printf "\n"
	@printf "\tdebug\n"
	@printf "\t    Compiles both the examples and driver in debug mode.\n"
	@printf "\n"
	@printf "\tclean\n"
	@printf "\t    Clean up all intermediate files generated by compilation\n"
	@printf "\t    of the driver and example programs.\n"
	@printf "\n"
	@printf "\tdriver\n"
	@printf "\t    Compiles the AXI DMA driver. The kernel object file can be\n"
	@printf "\t    found at \$$(OUTPUT_DIR)/axidma.ko.\n"
	@printf "\n"
	@printf "\tdriver_debug\n"
	@printf "\t    Compiles the AXI DMA driver in debug mode.\n"
	@printf "\n"
	@printf "\tdriver_clean\n"
	@printf "\t    Clean up files generated by the driver's compilation.\n"
	@printf "\n"
	@printf "\texamples, <example_name>\n"
	@printf "\t    Compiles the example programs or specific example program.\n"
	@printf "\t    The executable for a given example can be found at\n"
	@printf "\t    \$$(OUTPUT_DIR)/<example name>.\n"
	@printf "\n"
	@printf "\texamples_debug, <example_name>_debug\n"
	@printf "\t    Compiles the example programs or a specific example\n"
	@printf "\t    program in debug mode. This enables debugging symbols for\n"
	@printf "\t    GDB and compiles the program with -O0.\n"
	@printf "\n"
	@printf "\texamples_clean, <example_name>_clean\n"
	@printf "\t    Clean up files generated by compiling the examples or the\n"
	@printf "\t    specific example.\n"
	@printf "\n"
	@printf "\thelp\n"
	@printf "\t    Display this help message.\n"
	@printf "\n"
	@printf "Variables:\n"
	@printf "\tCROSS_COMPILE\n"
	@printf "\t    The prefix for the cross compiler to use for compilation.\n"
	@printf "\t    For example, \`arm-linux-gnueabi-\`. Not required; if left\n"
	@printf "\t    unspecified, then the system default compiler is used.\n"
	@printf "\n"
	@printf "\tARCH\n"
	@printf "\t    The architecture that the code is being compiled for.\n"
	@printf "\t    Only needed when cross-compiling the driver.\n"
	@printf "\n"
	@printf "\tKBUILD_DIR\n"
	@printf "\t    The path to the kernel source tree to build the driver\n"
	@printf "\t    against. Required when cross-compiling the driver.\n"
	@printf "\t    Otherwise, may be left unspecified. If it is, the system\n"
	@printf "\t    default is used.\n"
	@printf "\n"
	@printf "\tOUTPUT_DIR\n"
	@printf "\t    The path where the generated code files (both the kernel \n"
	@printf "\t    object file and executables) will be stored. The default \n"
	@printf "\t    is the "outputs" in the top-level directory.\n"
	@printf "\n"
	@printf "Examples:\n"
	@printf "\tmake\n"
	@printf "\tmake CROSS_COMPILE=arm-linux-gnueabi- ARCH=arm "
	@printf "KBUILD_DIR=/home/kernels/linux/ driver\n"
	@printf "\tmake CROSS_COMPILE=arm-linux-gnueabi- OUTPUT_DIR=outputs "
	@printf "examples\n"
	@printf "\tmake axidma_benchmark\n"
	@printf "\tmake OUTPUT_DIR=outputs clean\n"
