# Makefile
#
# Date: March 5, 2016
# Author: Brandon Perez
# Author: Jared Choi
#
# The top-level Makefile for the project, handles compilation for both the
# driver and the example application programs

###############################################################################
# Configuration
###############################################################################

# Location of the example programs, and the driver
DRIVER_DIR = driver
EXAMPLES_DIR = examples

# The location where the output executables and kernel object file will be
# stored. This may be overriden by the user
OUTPUT_DIR ?= outputs

# If either of the directory arguments were specified as relative paths, then
# fix them up since they will be referenced in Makefiles in lower directories
ifneq (/,$(shell echo $${OUTPUT_DIR:0:1}))
OUT_DIR := ../$(OUTPUT_DIR)
else
OUT_DIR := $(OUTPUT_DIR)
endif

ifdef KBUILD_DIR
ifneq (/,$(shell echo $${KBUILD_DIR:0:1}))
override KBUILD_DIR := ../$(KBUILD_DIR)
endif
endif

###############################################################################
# Targets
###############################################################################

# None of the targets correspond to actual files
.PHONY: all driver examples debug clean create_output_dir

# By default, compile the example files in release mode
all: create_output_dir driver examples

# Compile the axidma driver
driver:
	cd $(DRIVER_DIR) && make KBUILD_DIR=$(KBUILD_DIR) OUTPUT_DIR=$(OUT_DIR)

# Compile the example programs
examples debug:
	@cd $(EXAMPLES_DIR) && make OUTPUT_DIR=$(OUT_DIR) $@

# Clean up all temporary files
clean:
	@cd $(DRIVER_DIR) && make KBUILD_DIR=$(KBUILD_DIR) OUTPUT_DIR=$(OUT_DIR) \
		clean
	@cd $(EXAMPLES_DIR) && make OUTPUT_DIR=$(OUT_DIR) clean
	rm -rf $(OUTPUT_DIR)

# Display a help message to the user
help:
	@printf "Usage:\n"
	@printf "\tmake [target] [variable] ...\n"
	@printf "\n"
	@printf "Targets:\n"
	@printf "\tall\n"
	@printf "\t    The default target. Compiles both the examples and driver.\n"
	@printf "\n"
	@printf "\tdriver\n"
	@printf "\t    Compiles the AXI DMA driver. \n"
	@printf "\t    Kernel object file can be found at $(OUTPUT_DIR)/axidma.ko.\n"
	@printf "\n"
	@printf "\texamples\n"
	@printf "\t    Compiles the example programs for the AXI DMA driver.\n"
	@printf "\t    Generated executables can be found found in $(OUTPUT_DIR)/.\n"
	@printf "\n"
	@printf "\tdebug\n"
	@printf "\t    Compiles the example programs in debug mode, with symbols.\n"
	@printf "\n"
	@printf "\tclean\n"
	@printf "\t    Clean up all intermediate files generated by compilation.\n"
	@printf "\n"
	@printf "\thelp\n"
	@printf "\t    Display this help message.\n"
	@printf "\n"
	@printf "Variables:\n"
	@printf "\tCROSS_COMPILE\n"
	@printf "\t    The prefix for the cross compiler to use for compilation.\n"
	@printf "\t    For example, \`arm-linux-gnueabi-\`. Not required; if left\n"
	@printf "\t    unspecified, then the system default compiler is used.\n"
	@printf "\n"
	@printf "\tARCH\n"
	@printf "\t    The architecture that the code is being compiled for.\n"
	@printf "\t    Only needed when cross-compiling the driver.\n"
	@printf "\n"
	@printf "\tKBUILD_DIR\n"
	@printf "\t    The path to the kernel source tree to build the driver for.\n"
	@printf "\t    Required when cross-compiling the driver. Otherwise, may be\n"
	@printf "\t    left unspecified. If it is, the system default is used.\n"
	@printf "\n"
	@printf "\tOUTPUT_DIR\n"
	@printf "\t    The path where the generated code files (both the kernel \n"
	@printf "\t    object file and executables) will be stored. The default \n"
	@printf "\t    is the "outputs" in the top-level directory.\n"
	@printf "Examples:\n"
	@printf "\tmake\n"
	@printf "\tmake CROSS_COMPILE=arm-linux-gnueabi- ARCH=arm KBUILD_DIR=/home/kernels/linux/ driver\n"
	@printf "\tmake CROSS_COMPILE=arm-linux-gnueabi- examples\n"
	@printf "\tmake examples\n"
