# Makefile
#
# Date: March 5, 2016
# Author: Brandon Perez
# Author: Jared Choi
#
# The top-level Makefile for the project, handles compilation for both the
# driver and the example application programs

###############################################################################
# Configuration
###############################################################################

# Location of the example programs, and the driver
DRIVER_DIR = axidma
EXAMPLES_DIR = examples

###############################################################################
# Targets
###############################################################################

# None of the targets correspond to actual files
.PHONY: all driver examples debug clean

# By default, compile the example files in release mode
all: driver examples

# Compile the axidma driver
driver:
	@cd $(DRIVER_DIR) && make

# Compile the example programs
examples debug:
	@cd $(EXAMPLES_DIR) && make

# Clean up all temporary files
clean:
	@cd $(DRIVER_DIR) && make clean
	@cd $(EXAMPLES_DIR) && make clean

# Display a help message to the user
help:
	@echo "Usage:"
	@echo "\tmake [target] [variable] ..."
	@echo
	@echo "Targets:"
	@echo "\tall"
	@echo "\t    The default target. Compiles both the examples and driver."
	@echo
	@echo "\tdriver"
	@echo "\t    Compiles the AXI DMA driver. "
	@echo "\t    Kernel object file is generated at $(DRIVER_DIR)/axidma.ko."
	@echo
	@echo "\texamples"
	@echo "\t    Compiles the example programs for the AXI DMA driver."
	@echo "\t    Generated executables are found in $(EXAMPLES_DIR)."
	@echo
	@echo "\tdebug"
	@echo "\t    Compiles the example programs in debug mode, with symbols."
	@echo
	@echo "\tclean"
	@echo "\t    Clean up all intermediate files generated by compilation."
	@echo
	@echo "\thelp"
	@echo "\t    Display this help message."
	@echo
	@echo "Variables:"
	@echo "\tCROSS_COMPILE"
	@echo "\t    The prefix for the cross compiler to use for compilation."
	@echo "\t    For example, \`arm-linux-gnueabi-\`. Not required; if left"
	@echo "\t    unspecified, then the system default compiler is used."
	@echo
	@echo "\tARCH"
	@echo "\t    The architecture that the code is being compiled for."
	@echo "\t    Only needed when cross-compiling the driver."
	@echo
	@echo "\tKBUILD_DIR"
	@echo "\t    The path to the kernel source tree to build the driver for."
	@echo "\t    Required when cross-compiling the driver. Otherwise, may be"
	@echo "\t    left unspecified. If it is, the system default is used."
	@echo "Examples:"
	@echo "\tmake"
	@echo "\tmake CROSS_COMPILE=arm-linux-gnueabi- ARCH=arm KBUILD_DIR=/home/kernels/linux/ driver"
	@echo "\tmake CROSS_COMPILE=arm-linux-gnueabi- examples"
	@echo "\tmake examples"
